### ISSUE TITLE
How to use template defaults - from address and from name

### ISSUE THREAD

**Issue by marlonnelson** [renz45/mandrill_mailer#102]
Is there a way to use the defaults from the Mandrill template itself?

I don't want to specify either the from address or from name in my mailer.

The default subject works fine.

**Comment by marlonnelson** [comment]
Nevermind.  I read the code and found the solution.
```ruby
default from: nil
```

**Comment by renz45** [comment]
I apologize for the slow response, I'm glad that worked for you though. I've never thought about not sending a from, so that's good to know. :)
