### ISSUE TITLE
Using on my development machine

### ISSUE THREAD

**Issue by ianpetzer** [renz45/mandrill_mailer#106]
Hi there,

Thanks so much for this awesome gem. I've had some great success so far with sending Mandrill templated mails.

I was just wondering if there is any way to run this in 'development' mode similarly to the Rails Mailers where it logs to the console if a mail would've been sent.

I'm currently stopping the MandrillMailer from sending a mail by including: 'require 'mandrill_mailer/offline'' at the top of my development.rb environment file, but it would be great to see if a mail would've been sent.

Thanks,
Ian

**Comment by renz45** [comment]
Hi Ian,
There isn't anything currently like that for development, but it would be easy to make work. You could base it on the `offline` implementation, something like...

### mandrill_mailer/development.rb
```ruby
require 'mandrill_mailer'

module MandrillMailer
  class TemplateMailer
    def deliver
      deliver_now
    end
    def deliver_now
      puts "Template email sent: #{message}"
    end
    def deliver_later
      deliver_now
    end
  end

  class MessageMailer
    def deliver
      deliver_now
    end
    def deliver_now
      puts "Message email sent: #{message}"
    end
    def deliver_later
      deliver_now
    end
  end
end
```

Might want to format the message a bit so it isn't so large, but you get the idea. :)

Side note, if you get something working you like, feel free to pull request it to share with others. :)

**Comment by renz45** [comment]
I probably wouldn't want to make it run like this as a default, since a lot of people like to be able to send test emails from dev, but having the option would be nice.

**Comment by ianpetzer** [comment]
Hi @renz45,

Thats awesome. Thanks so much!
