### ISSUE TITLE
Emails rejected - unsigned

### ISSUE THREAD

**Issue by boparker** [renz45/mandrill_mailer#110]
I"m using mandrill in a wordpress application and they are all coming back rejected - unsigned. I have done the complete domain verification and have the verification email if you need it. I can also send just fine through the Send a Test Email dialogue and receive all of those. It's the emails generated by forms on my actual site that are being rejected. Any help would be great and be happy to PM or email with credentials for another set of eyes to have a look. Thanks,

**Comment by renz45** [comment]
Hi Parker, this repository is for a Ruby gem and not run by the actual Mandrill company, you're going to be better off contacting their support team to figure out your problem: https://mandrill.zendesk.com/hc/en-us
