### ISSUE TITLE
Mandrill Email Sending Failure

### ISSUE THREAD

**Issue by kalapvikas529** [renz45/mandrill_mailer#113]
Below is the response :
[0] => Array
        (
            [email] => test@test.com
            [status] => rejected
            [_id] => 4d9fba17f3ea47dca81381ae266d8d9b
            [reject_reason] => unsigned
        )

**Comment by renz45** [comment]
Hi there, this has to do with how Mandrill handles new accounts since December 2015, check out the message at the top of this page for more information: https://mandrillapp.com/api/docs/messages.html

Closing since this is unrelated to this gem. :grin:
