### ISSUE TITLE
Optionally not encode attachments and images

### ISSUE THREAD

**Issue by brunomperes** [renz45/mandrill_mailer#129]
I have a use case where my users submit base64 encoded files (to a RESTful service) and I then forward it to mandrill.

Since the gem automatically encodes all files, an option to not encode the files in certain cases would fit for that case, either from an option `:encoded_content` (mutually exclusive with `:content`) or a boolean `:encode_content` to not encode content before submitting.

I would be happy to submit a PR for this if the feature seems interesting.

**Comment by renz45** [comment]
That sounds reasonable, I would be happy to accept a PR for this. :) As long as its opt out (to stay compatible with current usage) it seems like a good feature to me.
