### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by gohuygo** [renz45/mandrill_mailer#132]
Are there any current plans in the pipeline for a Rails 5 implementation?

**Comment by renz45** [comment]
I think the biggest issue might be this: https://github.com/renz45/mandrill_mailer/issues/126

The mandrill team still hasn't updated that gem it in their api gem. I think other then that this should be usable in Rails 5.

**Comment by gohuygo** [comment]
Thanks for getting back quickly. Will probably give this a try since we're moving over to Rails 5 - unfortunately it's not supported by many gems yet. :)

**Comment by renz45** [comment]
I'm going to close this seeing as it's related to #126
