### ISSUE TITLE
Attachment not included in mail, yet no errors raised

### ISSUE THREAD

**Issue by jbwl** [renz45/mandrill_mailer#133]
I'd like some hints how I could debug this problem - I'm trying to send a mail with attachments as per the documentation. The mail is send out fine, with the correct template, but the attachment I sent with it is missing. There are no errors in the Rails log or in the Mandrill API logs, so I have no idea what could cause this.
How would you debug this?

**Comment by BenRuns** [comment]
This seems pretty difficult to debug or determine if more logging would add value without more information. 

Is it an intermittent failure? Can you replicate the error in development or test? If you've replicated it, have you set break points or print statements in the code to see what is going on?

**Comment by jbwl** [comment]
Closing it for now until I can find a way to get an error logged.
