### ISSUE TITLE
Version 1.8.0 not available on RubyGems

### ISSUE THREAD

**Issue by Kevinrob** [renz45/mandrill_mailer#143]
Hi 👋 

I don't see the recent version `1.8.0` on https://rubygems.org/gems/mandrill_mailer
Can you put this version on it?

Thanks!

**Comment by olivierlacan** [comment]
Now it is: https://rubygems.org/gems/mandrill_mailer/versions/1.8.0

🤗

**Comment by Kevinrob** [comment]
> Now it is: https://rubygems.org/gems/mandrill_mailer/versions/1.8.0
> 
> 🤗

Thank you!
