### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by cjshort** [renz45/mandrill_mailer#77]
mailers/panel_mailer.rb

class PanelMailer < MandrillMailer::TemplateMailer

  def blast(user, template)
    humans = user.humans
    mandrill_mail(
      template: 'blast-1',
      subject: template.subject,
      to: [
        { email: "callumshorty@hotmail.com", name: "Callum Short" }
        ],
      vars: {
        'BG_COLOUR' => "##{user.bghex}",
        'LOGO' => user.logourl_url
      },
      template_content: {'body' => template.body},
      inline_css: true,
      preserve_recipients: true,
      recipient_vars: [{"callumshorty@hotmail.com" => {'FULL_NAME' => "Callum Short"}}]
      )
  end
end

Any ideas what's going wrong here? I get the error when triggering the mailer via a create action.

**Comment by olivierlacan** [comment]
@cjshort It's easier to help you when your code is legible:

```ruby
class PanelMailer < MandrillMailer::TemplateMailer

  def blast(user, template)
    humans = user.humans
    mandrill_mail(
      template: 'blast-1',
      subject: template.subject,
      to: [
        { email: "callumshorty@hotmail.com", name: "Callum Short" }
        ],
        vars: {
          'BG_COLOUR' => "##{user.bghex}",
          'LOGO' => user.logourl_url
          },
          template_content: {'body' => template.body},
          inline_css: true,
          preserve_recipients: true,
          recipient_vars: [{"callumshorty@hotmail.com" => {'FULL_NAME' => "Callum Short"}}]
          )
  end
end
```

**Comment by olivierlacan** [comment]
@cjshort Also could you please provide a full backtrace of that `undefined method` exception. I'm guessing the class it originates from is `CoreMailer` but I'd like to be sure.

**Comment by cjshort** [comment]
Hi @olivierlacan, sorry about the formatting I'm not too used to github.

I've created a stackoverflow post for you which hopefully is easier to work with, included is the backtrace as well: http://stackoverflow.com/questions/29692251/undefined-method-for-nilnilclass-on-mandrill-mailer
