### ISSUE TITLE
How can I capture response JSON?

### ISSUE THREAD

**Issue by cjshort** [renz45/mandrill_mailer#79]
The Mandrill API (https://mandrillapp.com/api/docs/messages.html) states a response JSON is provided containing valuable information such as the id and status of the email - How can I capture this?

**Comment by renz45** [comment]
We are just using the mandrill api gem behind the scenes for this. According to their documentation, the `#send` method returns the data you're looking for, we call send here: https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/message_mailer.rb#L110

So you should be able to handle the returned object from the deliver method. You'll have to do this in your delayed job though.
