### ISSUE TITLE
TypeError when no merge vars are sent to mandrill_mail

### ISSUE THREAD

**Issue by olivierlacan** [renz45/mandrill_mailer#83]
I've identified a regression caused by my recent PR (#72).

When calling `mandrill_mail` without merge vars like:

```ruby
mandrill_mail template: 'Expiration Post',
                    subject: "Blabla",
                    to: { email: options[:email], name: options[:name] }
```

`mandrill_args` is called with `nil` in [`TemplateMailer#mandrill_mail`](https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/template_mailer.rb#L186)

`mandrill_args` attempts to call `merge_default_merge_vars` with `nil` in [`CoreMailer#mandrill_args`](https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/core_mailer.rb#L329).

Which finally explodes in [`CoreMailer#merge_default_merge_vars`](https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/core_mailer.rb#L346) when we call:

```ruby
self.class.defaults[:merge_vars].merge(args)
```

Because `args == nil` And `{}.merge(nil)` triggers a type error.

The solution I see is to do this:

```ruby
def merge_default_merge_vars(args)
  return self.class.defaults[:merge_vars] unless args
  self.class.defaults[:merge_vars].merge(args)
end
```

Does that make sense @renz45?

**Comment by renz45** [comment]
```ruby
def merge_default_merge_vars(args)
  if args
    self.class.defaults[:merge_vars].merge(args)
  else
    self.class.defaults[:merge_vars]
  end
end
```

Might be clearer, but the logic seems solid :+1:

**Comment by olivierlacan** [comment]
Alright. I'll take care of it later tonight.

**Comment by arronmabrey** [comment]
you could use `args || {}`
```ruby
def merge_default_merge_vars(args)
  self.class.defaults[:merge_vars].merge(args || {})
end
```

in ruby 2, `nil` responds to `#to_h`

```ruby
def merge_default_merge_vars(args)
  self.class.defaults[:merge_vars].merge args.to_h
end
```

Miss you guys :heart_eyes:

**Comment by arronmabrey** [comment]
To clarify, in ruby 2.
```ruby
nil.to_h
#=> {}
```
