### ISSUE TITLE
mailer.data not accessible after 1.0?

### ISSUE THREAD

**Issue by olivierlacan** [renz45/mandrill_mailer#88]
We have the following `from_matcher` on Code School which was calling the following:

```ruby
# ...
def mailer_from_email(mailer)
    mailer.data['message']['from_email']
  end

  def mailer_from_name(mailer)
    mailer.data['message']['from_name']
  end
end
```

The calls to `mailer.data` used to succeed prior to 1.0 but no longer work. It seems like swapping them out for  `mailer.message["from_email"]` and `mailer.message["from_name"]` works fine.

I'm just documenting this here for people who might encounter the same issue with their existing RSpec matchers.

**Comment by renz45** [comment]
ahh I know now, the `.data` call was marked as deprecated in the post recent pre 1.0 code, so in 1.0 i removed it completely.
