### ISSUE TITLE
documentation request - what happens if there is an error?

### ISSUE THREAD

**Issue by ConfusedVorlon** [renz45/mandrill_mailer#89]
can we assume that if there is a problem sending, then an error will be thrown?

I have tested for 'network down' and 'bad api key', but it would be great to get confirmation that this is always the case.

e.g. if I don't get an error, can I mark my email as successfully queued with mandril?

thanks.

**Comment by renz45** [comment]
I'm assuming this is the case. I apologize for being a bit vague, but the api gem seems to change/be rewritten a lot, which things like errors hard to nail down. For the current version, it looks like the official api gem is handling quite a few errors judging by the [source](https://bitbucket.org/mailchimp/mandrill-api-ruby/src/51193ecc8adb155a384d0a3e0a44341f0c3a28dd/lib/mandrill/errors.rb?at=master)

**Comment by ConfusedVorlon** [comment]
thanks. - and thanks for a handy gem!

**Comment by renz45** [comment]
Np! Glad I could help.
