### ISSUE TITLE
Attachment Content

### ISSUE THREAD

**Issue by jsanders67** [renz45/mandrill_mailer#90]
This is a stupid question, but I have looked everywhere for an answer.

What exactly does the attachment content need to be? I am using paperclip and I'm not totally sure what specific content (base64,etc.) we are supposed to pass in. Any help would be greatly appreciated

**Comment by renz45** [comment]
Looks like we do the base64 encoding for you at: https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/arg_formatter.rb#L14

I'm thinking it just needs the binary file (I think my original use case was just Ruby's File.read), sort of less then ideal for your use case and paperclip. Any idea what a good alternative would be?

**Comment by jsanders67** [comment]
I used File.read(object.image.path), and it works. Im not sure if this is the best way either but seems to get the job done

**Comment by renz45** [comment]
:+1:
