### ISSUE TITLE
Active Job Support

### ISSUE THREAD

**Issue by dmpawlowski** [renz45/mandrill_mailer#91]
Are there currently any plans for this to work with Active Job? I know the "deliver" method will be deprecated and the deliver_now and deliver_later methods don't currently work with the template mailer. Thanks!

**Comment by renz45** [comment]
Good question! I will confess I haven't had to opportunity to use Active Job yet, I'll could probably dig into Rails a bit to see how we could hook into it. Unless of course if someone beats me to it with a pull request. :D

I'll likely look into after Active Job ships though, I can't imagine it being too tough to support. :)

**Comment by renz45** [comment]
I'll leave this open to remind myself  :) Thanks for suggesting it.

**Comment by renz45** [comment]
We can probably include: https://github.com/rails/rails/blob/4-2-stable/actionmailer/lib/action_mailer/message_delivery.rb

and ensure that a few methods that it expects exist.

**Comment by dmpawlowski** [comment]
@renz45 have you made any strides on this? If not, I'm going to try to put a PR together today.

**Comment by renz45** [comment]
I haven't started any code yet, if you wanted to do a PR that would be great :)

**Comment by dmpawlowski** [comment]
@renz45 I hate to bail on you, but we ended up going a different direction with our app. Good luck!

**Comment by renz45** [comment]
No worries, I'll leave this open and add it in some time soon. Thanks again for bringing it up.

**Comment by BenRuns** [comment]
I added this on my last commit to https://github.com/BenRuns/mandrill_mailer/commit/555278aba0dc1e9d23837816ba471de30c0ec987

**Comment by renz45** [comment]
Looks great Ben! If you wanted to submit a pull request with that I would accept it. :) I'd only make one very small change, alias `deliver` to `deliver_now` so we don't need to bump a major.

**Comment by BenRuns** [comment]
done and done

**Comment by renz45** [comment]
closed via https://github.com/renz45/mandrill_mailer/pull/104

**Comment by renz45** [comment]
Thanks ben!
