### ISSUE TITLE
How to catch rejected mail reason?

### ISSUE THREAD

**Issue by xtagon** [renz45/mandrill_mailer#95]
Hi,

Sometimes the Mandrill API returns the status as rejected. What's the best way for me to detect this (or any other status) in the API response in my app? Specifically I would like to catch those situations and report it to my exception tracker.

Here is an example API response:

```json
[
    {
        "email": "user@example.org",
        "status": "rejected",
        "_id": "SOME_ID",
        "reject_reason": "invalid-sender"
    }
]
```

I'm using the template mailer in a Rails app.

Any ideas? Thanks :-)

**Comment by renz45** [comment]
Hi there, the mandrill people aren't great at documenting this sort of thing, but you should be able to rescue the error and handle it how you want. Check out this file for a list of the possible errors (although you might have to make some guesses as to which get triggered where) : https://bitbucket.org/mailchimp/mandrill-api-ruby/src/044396ea8f760a617a1b62e28f69b77833d82d55/lib/mandrill/errors.rb?at=master&fileviewer=file-view-default

**Comment by renz45** [comment]
err I might have misunderstood the question :D Give me a minute ;)

**Comment by xtagon** [comment]
No problem. To clarify, in my situation the Mandrill API counts it as a successful API call so no error is thrown. However, the mail actually is rejected because the sender name is missing. This was hard for me to debug because my app never knew there was a configuration problem, it just silently failed to send the mail. So what I'd like to do is have my app check the API response and handle rejection status.

**Comment by renz45** [comment]
You should get a that response back from the deliver method, so in the job you could do something like this with delayed job and bugsnag..

```ruby
class UpdateEmailJob < Struct.new(:user_id)
  def perform
    user = User.find(user_id)
    response = HallpassMailer.hallpass_expired(user).deliver

    if response['status'] == 'rejected'
      Bugsnag.notify(StandardError.new("Email to #{response['email']} was rejected for reason: #{response['reject_reason']}"))
    end   
  end
end
```

**Comment by xtagon** [comment]
Perfect, I'll give it a try later. Thanks!

**Comment by renz45** [comment]
You could probably just raise the error instead of calling bugsnag directly as well (I think)

**Comment by renz45** [comment]
Great!
