### ISSUE TITLE
Defaults set on a child class wipe out all defaults form the parent class

### ISSUE THREAD

**Issue by olivierlacan** [renz45/mandrill_mailer#99]
Example:

```ruby
class MailerBase < MandrillMailer::TemplateMailer
  default from: "email@example.com",
          from_name: "Example",
          view_content_link: true
end

class FunMailer < MailerBase
  default view_content_link: false
end
```

The `FunMailer` will now have `from_name` and `from` reset to the mandrill_mailer defaults, not the MailerBase. So basically we need to fix this: https://github.com/renz45/mandrill_mailer/blob/5cae59e0f91cf3aedba85c37afde310be09af1a8/lib/mandrill_mailer/core_mailer.rb#L154-L159

From this:

```ruby
def self.default(args)
      @defaults ||= {}
      @defaults[:from] ||= 'example@email.com'
      @defaults[:merge_vars] ||= {}
      @defaults.merge!(args)
    end
```

To this:

```ruby
def self.default(args)
      @defaults ||= {}
      @defaults[:from] ||= (super_defaults[:from] || 'example@email.com')
      @defaults[:merge_vars] ||= (super_defaults[:merge_vars]|| {})
      @defaults.merge!(args)
    end
```

Makes sense? @renz45 @katiedelfin

**Comment by renz45** [comment]
Odd... usually using `@` inside a class method will me local to the current top level class, while using `@@` would pollute the entire inheritance chain. I wonder if its a newer version of ruby that changes this behavior?

**Comment by olivierlacan** [comment]
That would probably show up in the Travis build Matrix if it were recent Ruby related. No?

**Comment by renz45** [comment]
Dumb little example:

```ruby
class One
  def self.set_one
    @test = "this is one"
  end

  def self.one
    @test
  end
end

class Two < One
  def self.set_two
    @test = "this is two"
  end
end
```

```
One.one
> nil

One.set_one
One.one
> "this is one"

Two.one
> nil

Two.set_two
Two.one
> "this is two"

One.one
> "this is one"
```

works for me in 2.0.0-p353

**Comment by renz45** [comment]
Going to close this, feel free to reopen if it pops back up.
